app:
  cookie_expiration_ms: 3600000 # 60 min
  secure_token_validity_sec: 28800

server:
  port: 8080

spring:
  application:
    name: onsen-auth-service
  config:
    import: "optional:configserver:http://localhost:8071/"
  sql:
    init:
      mode: always  # use schema.sql and data.sql on init.
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true  # show in the logs whenever sql query gets executed
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
#    url: jdbc:postgresql://gateway.docker.internal:5433/my_db
    username: postgres
    password: root

#logging:
#  level:
#    org.springframework.security.web.FilterChainProxy: DEBUG

#
#build-info:
#  appName: ${spring.application.name}
#  environment: local