#version: '3.1'
#
#services:
#  db:
#    image: postgres # from docker-hub
#    restart: always
#    ports:
#      - "5433:5432" # first one is the one where it is accessible, the 2nd is where it is stored in the docker network.
#    environment:
#      POSTGRES_USERNAME: postgres
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: my_db
