#FROM eclipse-temurin:17.0.11_9-jre-ubi9-minimal
## Information who maintains the image
#MAINTAINER example.com
#
## Add the app's jar to the image
#COPY target/onsen-auth-service-0.0.1-SNAPSHOT.jar onsen-auth-service.jar
#
## let image be accessible from localhost:8081
#EXPOSE 8081
#
## Execute the application
#ENTRYPOINT ["java", "-jar", "onsen-auth-service.jar"]
