# Should be applied to all the application in this directory

build-info:
  appName: ${spring.application.name}
  environment: default

spring:
  cloud:
    bus:
      enabled: on
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"  # tell actuator to expose all endpoints, including refresh.
  health:
    readiness-state:  # /actuator/health/readiness
      enabled: true
    liveness-state:   # /actuator/health/liveness
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
    env:
      show-values: ALWAYS
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true # POST -> /actuator/shutdown

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true       # by default true, here false since the eureka server doesn't need to fetch the registry, it is the registry?
    registerWithEureka: true  # by default true, here false since it shouldn 't register itself
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        cloud:
          openfeign: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    feign: DEBUG

