app:
  cookie_expiration_ms: 3600000 # 60 min
#  Filterchainproxy debug spring app properties


server:
  port : 8082
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#spring:
#  sql:
#    init:
#      mode: always  # use schema.sql and data.sql on init. Turn off since it runs them already using databaseInitializer
#  jpa:
#    hibernate:
#      show-sql=true:
#      ddl-auto: none # Do not auto create tables
#      properties:
#        globally_quoted_identifiers: true


spring:
  mvc:
    log-request-details: true
  sql:
    init:
      mode: always  # use schema.sql and data.sql on init. Turn off since it runs them already using databaseInitializer
  jpa:
    hibernate:
#      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true  # show in the logs whenever sql query gets executed
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_auth
    username: postgres
    password: root


logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG



