server:
  port : 8082
#  spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring:
  sql:
    init:
      mode: never  # use schema.sql and data.sql on init. Turn off since it runs them already using databaseInitializer
  jpa:
    hibernate:
      show-sql=true:
      ddl-auto: none # Do not auto create tables


  datasource:
#    url: jdbc:mysql://localhost:3306/jwt_auth
#    password: root
#    username: root
    url: jdbc:postgresql://localhost:5432/jwt_auth
    username: postgres
    password: root


logging:
  level:
    org:
      springframework:
        web: DEBUG
