server:
  port : 8082

spring:
  jpa:
    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_auth
    password: root
    username: root

logging:
  level:
    org:
      springframework:
        web: DEBUG
