-- DROP TABLE IF EXISTS "users" CASCADE;   -- CASCADE also deletes the dependent data (since users and authorities are linked).
-- DROP TABLE IF EXISTS "roles";
--
-- CREATE TABLE "users"
-- (
--     username VARCHAR(100) NOT NULL,
--     password CHAR(68) DEFAULT NULL,
--     enabled  BOOLEAN NOT NULL,
--
--     PRIMARY KEY (username)
-- );
--
--
-- CREATE TABLE "roles"
-- (
--     username  VARCHAR(50) NOT NULL,
--     authority VARCHAR(50) NOT NULL,
--
--     CONSTRAINT fk_authorities_users
--     FOREIGN KEY (username)
--     REFERENCES users (username)
-- );
--
-- create unique index ix_auth_username on authorities (username, authority);
--
