//package enums;
//
//import lombok.Getter;
//
//@Getter
//public enum AnimationStateEnum {
//    IDLE_TOP("IDLE_TOP"), IDLE_TOP_RIGHT("IDLE_TOP_RIGHT"), IDLE_RIGHT("IDLE_RIGHT"), IDLE_BOTTOM_RIGHT("IDLE_BOTTOM_RIGHT"),
//    IDLE_BOTTOM("IDLE_BOTTOM"), IDLE_BOTTOM_LEFT("IDLE_BOTTOM_LEFT"), IDLE_LEFT("IDLE_LEFT"), IDLE_TOP_LEFT("IDLE_TOP_LEFT"),
//    WALK_TOP("WALK_TOP"), WALK_TOP_RIGHT("WALK_TOP_RIGHT"), WALK_RIGHT("WALK_RIGHT"), WALK_BOTTOM_RIGHT("WALK_BOTTOM_RIGHT"),
//    WALK_BOTTOM("WALK_BOTTOM"), WALK_BOTTOM_LEFT("WALK_BOTTOM_LEFT"), WALK_LEFT("WALK_LEFT"), WALK_TOP_LEFT("WALK_TOP_LEFT"),
//    SHOOT_TOP("SHOOT_TOP"), SHOOT_TOP_RIGHT("SHOOT_TOP_RIGHT"), SHOOT_RIGHT("SHOOT_RIGHT"), SHOOT_BOTTOM_RIGHT("SHOOT_BOTTOM_RIGHT"),
//    SHOOT_BOTTOM("SHOOT_BOTTOM"), SHOOT_BOTTOM_LEFT("SHOOT_BOTTOM_LEFT"), SHOOT_LEFT("SHOOT_LEFT"), SHOOT_TOP_LEFT("SHOOT_TOP_LEFT");
//
//    private final String text;
//
//    AnimationStateEnum(final String text) {
//        this.text = text;
//    }
//
//    @Override
//    public String toString() {
//        return getText();
//    }
//}
