server:
  port: 8082
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/onsen-localhost.p12
    key-store-password: rootroot
    key-alias: localhost


logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE # Log what values are put in the db


spring:
  application:
    name: onsen-main
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop  # drop database and generate automatically
    generate-ddl: true  # generate database automatically
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # show in the logs whenever sql query gets executed
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root